# Generated by Django 5.2.7 on 2025-12-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('category', 'Category Offer'), ('product', 'Product Offer'), ('amount_threshold', 'Amount Threshold Offer')], max_length=20),
        ),
    ]
