# Generated by Django 5.2.7 on 2025-12-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_coupons', '0002_alter_offer_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='limit',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
