# Generated by Django 5.2.7 on 2025-12-15 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_coupons', '0004_alter_offer_options_rename_used_offer_usage_limit_and_more'),
        ('products', '0004_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='products.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='products.product'),
        ),
    ]
