# Generated by Django 5.2.7 on 2025-12-15 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_coupons', '0005_alter_offer_category_alter_offer_product'),
        ('order', '0012_remove_ordermain_payment_id_ordermain_is_paid_and_more'),
        ('products', '0004_alter_product_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='offerusage',
            unique_together={('offer', 'user', 'order')},
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='offers', to='products.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='offers', to='products.product'),
        ),
    ]
