# Generated by Django 5.2.7 on 2025-12-16 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_coupons', '0006_offer_min_order_amount_remove_offer_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='product',
            new_name='products',
        ),
    ]
