# Generated by Django 5.2.7 on 2025-12-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_coupons', '0007_rename_category_offer_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='display_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
