# Generated by Django 5.2.7 on 2025-12-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_coupons', '0008_offer_display_in_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='display_in_home',
            new_name='display_home',
        ),
    ]
