# Generated by Django 5.2.7 on 2025-12-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_coupons', '0009_rename_display_in_home_offer_display_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerusage',
            old_name='is_active',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='offerusage',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='offer_coupons.offer'),
        ),
    ]
