# Generated by Django 5.2.7 on 2026-02-02 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, help_text="Code users enter (e.g., 'SUMMER20')", max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{3,15}$', 'Coupon code must be 3–15 uppercase letters or numbers.')]),
        ),
    ]
