# Generated by Django 5.2.7 on 2026-02-02 06:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.RegexValidator('^[0-9]{1,10}$', 'Coupon amount must be a positive number')]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00')), django.core.validators.RegexValidator('^[0-9]{1,5}$', 'Coupon percentage must be a positive number')]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.RegexValidator('^[0-9]{1,10}$', 'Minimum purchase amount must be a positive number')]),
        ),
    ]
