# Generated by Django 5.2.7 on 2026-02-02 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_code_alter_coupon_coupon_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(help_text="Internal name (e.g., 'Summer Sale 2024')", max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 ]{3,100}$', 'Name must be 3–100 characters long and can only contain letters, numbers, and spaces.')]),
        ),
    ]
