# Generated by Django 5.2.7 on 2026-02-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_coupon_amount_and_more'),
        ('coupon', '0004_alter_coupon_coupon_amount_and_more'),
    ]

    operations = [
    ]
