# Generated by Django 5.2.7 on 2025-12-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='min_order_amount',
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('fixed_amount', 'Fixed Amount')], max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('category', 'Category Offer'), ('product', 'Product Offer')], max_length=20),
        ),
    ]
