# Generated by Django 5.2.7 on 2026-01-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_remove_offer_min_order_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
