# Generated by Django 5.2.7 on 2026-01-08 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_offer_end_date'),
        ('order', '0018_cancelitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerusage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_used', to='order.ordermain'),
        ),
    ]
