# Generated by Django 5.2.7 on 2026-02-02 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_alter_offerusage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount_value',
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage')], max_length=20),
        ),
    ]
