# Generated by Django 5.2.7 on 2026-02-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_remove_offer_discount_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('fixed_amount', 'Fixed Amount')], max_length=20),
        ),
    ]
