# Generated by Django 5.2.7 on 2026-02-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_remove_offer_discount_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
