# Generated by Django 5.2.7 on 2026-02-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_alter_offer_discount_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='description',
            new_name='title',
        ),
    ]
