# Generated by Django 5.2.7 on 2025-12-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_price_at_purchasae_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermain',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='ordermain',
            old_name='final_amount',
            new_name='final_price',
        ),
        migrations.RenameField(
            model_name='ordermain',
            old_name='shipping_address',
            new_name='shipping_address_line_1',
        ),
        migrations.RenameField(
            model_name='ordermain',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='ordermain',
            name='shipping_address_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermain',
            name='shipping_city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermain',
            name='shipping_phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermain',
            name='shipping_pincode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermain',
            name='shipping_state',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('return_requested', 'Return Requested'), ('partially_cancelled', 'Partially cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
