# Generated by Django 5.2.7 on 2025-12-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordermain_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermain',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
        ),
    ]
