# Generated by Django 5.2.7 on 2025-12-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_is_returned_ordermain_shippint_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='user',
            field=models.CharField(max_length=250),
        ),
    ]
