# Generated by Django 5.2.7 on 2025-12-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_returnorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermain',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
