# Generated by Django 5.2.7 on 2025-12-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_shippint_amount_ordermain_shipping_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='return_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
