# Generated by Django 5.2.7 on 2025-12-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_returnorder_return_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_item', to='order.orderitem'),
        ),
    ]
