# Generated by Django 5.2.7 on 2025-12-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_returnorder_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('return_approved', 'Return Approved'), ('return_requested', 'Return Requested'), ('return_rejected', 'Return Rejected'), ('partially_returned', 'Partially Returned'), ('partially_cancelled', 'Partially cancelled'), ('return_canceled', 'Return Canceled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('return_approved', 'Return Approved'), ('return_requested', 'Return Requested'), ('return_rejected', 'Return Rejected'), ('partially_returned', 'Partially Returned'), ('partially_cancelled', 'Partially cancelled'), ('return_canceled', 'Return Canceled')], default='pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='return_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('returned', 'Returned'), ('return_requested', 'Return Requested'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('return_canceled', 'Return Canceled')], default='pending', max_length=50),
        ),
    ]
