# Generated by Django 5.2.7 on 2025-12-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_ordermain_payment_id_ordermain_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermain',
            name='tax_amount',
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
        ),
    ]
