# Generated by Django 5.2.7 on 2025-12-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_ordermain_expires_at_alter_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermain',
            name='wallet_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Amount deducted from user's wallet", max_digits=10),
        ),
    ]
