# Generated by Django 5.2.7 on 2025-12-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_ordermain_wallet_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermain',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
