# Generated by Django 5.2.7 on 2026-01-07 07:06

import django.db.models.deletion
import userFolder.order.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_ordermain_coupon_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_id', models.CharField(default=userFolder.order.models.generate_cancel_id, editable=False, max_length=50, unique=True)),
                ('is_full_cancel', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cancel_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='order.ordermain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
