# Generated by Django 5.2.7 on 2026-01-07 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_cancelorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancel_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.cancelorder')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_entries', to='order.orderitem')),
            ],
        ),
    ]
