# Generated by Django 5.2.7 on 2026-01-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_cancelitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('return_approved', 'Return Approved'), ('return_requested', 'Return Requested'), ('return_rejected', 'Return Rejected'), ('partially_returned', 'Partially Returned'), ('partially_cancelled', 'Partially cancelled'), ('return_canceled', 'Return Canceled'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='order_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('return_approved', 'Return Approved'), ('return_requested', 'Return Requested'), ('return_rejected', 'Return Rejected'), ('partially_returned', 'Partially Returned'), ('partially_cancelled', 'Partially cancelled'), ('return_canceled', 'Return Canceled'), ('failed', 'Failed')], default='draft', max_length=150),
        ),
    ]
