# Generated by Django 5.2.7 on 2026-01-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_orderitem_status_alter_ordermain_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermain',
            options={'ordering': ['-last_item_updated_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordermain',
            name='last_item_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
