# Generated by Django 5.2.7 on 2025-11-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_is_verified_customuser_is_verfied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verfied',
            new_name='is_verified',
        ),
    ]
