# Generated by Django 5.2.7 on 2026-01-31 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_is_verfied_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters.', regex='^[A-Za-z]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters.', regex='^[A-Za-z]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a valid 10-digit Indian phone number.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
