# Generated by Django 5.2.7 on 2026-01-31 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters, spaces, and hyphens.', regex='^[A-Za-z\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters, spaces, and hyphens.', regex='^[A-Za-z\\s-]+$')]),
        ),
    ]
