# Generated by Django 5.2.7 on 2026-02-02 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_referral_used_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters', regex='^[A-Za-z\\s]+$')]),
        ),
    ]
