# Generated by Django 5.2.7 on 2025-12-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
