# Generated by Django 5.2.7 on 2025-12-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_address_address_line_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('HOME', 'Home'), ('WORK', 'Work/Office'), ('OTHER', 'Other')], default='HOME', max_length=50),
        ),
    ]
