# Generated by Django 5.2.7 on 2025-12-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('HOME', 'Home'), ('WORK', 'Work/Office'), ('OTHER', 'Other')], default='HOME', max_length=50, null=True),
        ),
    ]
