# Generated by Django 5.2.7 on 2026-02-02 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='invalid_address_line', message='Enter a valid address line (only letters, numbers and , . / # - ( ) allowed).', regex='^[A-Za-z0-9\\s,./#\\-()]+$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='invalid_address_line', message='Enter a valid address line (only letters, numbers and , . / # - ( ) allowed).', regex='^[A-Za-z0-9\\s,./#\\-()]+$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a valid 10-digit Indian phone number.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_postal_code', message='Enter a valid 6-digit postal code.', regex='^[0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters', regex='^[A-Za-z\\s]+$')]),
        ),
    ]
