# Generated by Django 5.2.7 on 2025-12-08 06:00

import userFolder.wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=userFolder.wallet.models.generate_transaction_id, editable=False, max_length=100, unique=True, verbose_name='Transaction ID'),
        ),
    ]
