# Generated by Django 5.2.7 on 2025-12-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('COMP', 'Completed'), ('FL', 'Failed'), ('RF', 'Refunded')], default='PD', max_length=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CR', 'Credit'), ('DB', 'Debit')], max_length=6, verbose_name='Type'),
        ),
    ]
