# Generated by Django 5.2.7 on 2025-12-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_alter_referral_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralusage',
            name='status',
            field=models.CharField(choices=[('Rewarded', 'Rewarded'), ('Active', 'Active'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
