# Generated by Django 5.2.7 on 2025-11-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options_alter_cartitems_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='product',
            new_name='variant',
        ),
    ]
