# Generated by Django 5.2.7 on 2025-11-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_product_cartitems_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='item_added',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
