# Generated by Django 5.2.7 on 2025-11-29 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_options_alter_cartitems_item_added'),
        ('products', '0003_product_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('cart', 'variant', 'size')},
        ),
    ]
