# Generated by Django 5.2.7 on 2025-12-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitems_unique_together'),
        ('products', '0004_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('cart', 'variant')},
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='item_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='size',
        ),
    ]
