# Generated by Django 5.2.7 on 2025-12-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartitems_unique_together_and_more'),
        ('products', '0004_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='item_added',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('cart', 'variant', 'size')},
        ),
    ]
