# Generated by Django 5.2.7 on 2025-11-29 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_base_price_remove_product_offer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=datetime.datetime(2025, 11, 29, 3, 47, 3, 628473, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
