# Generated by Django 5.2.7 on 2025-12-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariant_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_price',
        ),
    ]
