# Generated by Django 5.2.7 on 2026-01-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='subject',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
