# Generated by Django 5.2.7 on 2026-01-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_contactmodel_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
