# Generated by Django 5.2.7 on 2026-01-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_contactmodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_most_demanded',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_selective',
        ),
    ]
