# Generated by Django 5.2.7 on 2026-01-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_is_most_demanded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbanails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_showen', models.BooleanField(default=False)),
            ],
        ),
    ]
