# Generated by Django 5.2.7 on 2026-01-11 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_thumbanails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbanails',
            old_name='is_showen',
            new_name='is_visible',
        ),
        migrations.AddField(
            model_name='thumbanails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thumbanails',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
