# Generated by Django 5.2.7 on 2026-01-24 14:39

import products.contact_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_is_showen_thumbanails_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbanails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.contact_models.get_file_path),
        ),
        migrations.AlterField(
            model_name='thumbanails',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
