# Generated by Django 5.2.7 on 2026-02-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_thumbanails_image_alter_thumbanails_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='in_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
