# Generated by Django 5.2.7 on 2026-02-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_in_cart_product_in_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_cart',
        ),
    ]
