# Generated by Django 5.2.7 on 2026-02-02 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_in_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=1024, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters', regex='^[A-Za-z\\s]+$')]),
        ),
    ]
