# Generated by Django 5.2.7 on 2026-02-02 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_category_name_alter_product_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_alt_text', message='Alt text must contain only letters', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='invalid_description', message='Description must contain contain letters, numbers, spaces and - & ( ) [ ] / . + ,', regex='^[A-Za-z0-9\\s\\-\\&\\(\\)\\[\\]\\/\\.\\+\\,]+$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(code='invalid_product_name', message='Product name can contain letters, numbers, spaces and - & ( ) [ ] / . + ,', regex='^[A-Za-z0-9\\s\\-\\&\\(\\)\\[\\]\\/\\.\\+\\,]+$')]),
        ),
    ]
